import type { Reservation, TableState } from '@/features/staff/types';

export const initialTables: TableState[] = [
    {
        id: 1,
        name: 'Table 1',
        capacity: 2,
        status: 'Occupied',
        statusLabel: 'Occupied',
        partyInfo: 'Sara Lindqvist, 2 guests',
        timeSlot: '18:30–20:30',
        image: '/images/dining-table.png',
        location: 'Window alcove • South facing',
    },
    {
        id: 2,
        name: 'Table 2',
        capacity: 2,
        status: 'Open',
        statusLabel: 'Open',
        partyInfo: 'Available for walk-in',
        timeSlot: 'Free until 20:00',
        image: '/images/dining-room.png',
        location: 'Main dining room • Center floor',
    },
    {
        id: 3,
        name: 'Table 3',
        capacity: 4,
        status: 'Reserved',
        statusLabel: 'Reserved 19:00',
        partyInfo: 'Henrik Berg, 4 guests',
        timeSlot: '19:00–21:00',
        image: '/images/dining-table.png',
        location: 'East wall • Leather banquette',
    },
    {
        id: 4,
        name: 'Table 4',
        capacity: 4,
        status: 'Open',
        statusLabel: 'Open',
        partyInfo: 'Available for walk-in',
        timeSlot: 'Free all evening',
        image: '/images/lunch.png',
        location: 'West side • Garden atrium view',
    },
    {
        id: 5,
        name: 'Table 5',
        subtitle: 'The Long Table',
        capacity: 6,
        status: 'Reserved',
        statusLabel: 'Reserved 19:00',
        partyInfo: 'Elena Rost, 6 guests',
        timeSlot: '19:00–21:00',
        image: '/images/long-table.png',
        location: 'Private bay • Oak communal table',
    },
];

export const initialReservations: Reservation[] = [
    {
        id: 'res-1',
        time: '18:30',
        guestName: 'Sara Lindqvist',
        email: 'sara@example.com',
        phone: '+46 70 123 4567',
        table: 'Table 1',
        partySize: 2,
        status: 'Seated',
        service: 'Dinner',
        notes: 'Window preference • Celebrating quiet dinner',
    },
    {
        id: 'res-2',
        time: '19:00',
        guestName: 'Henrik Berg',
        email: 'henrik.berg@nordic.se',
        phone: '+46 70 234 5678',
        table: 'Table 3',
        partySize: 4,
        status: 'Confirmed',
        service: 'Dinner',
        notes: 'Wedding anniversary',
    },
    {
        id: 'res-3',
        time: '19:00',
        guestName: 'Elena Rost',
        email: 'elena@rost.design',
        phone: '+46 73 987 6543',
        table: 'Table 5 (The Long Table)',
        partySize: 6,
        status: 'Confirmed',
        service: 'Dinner',
        notes: 'Private tasting menu requested',
    },
    {
        id: 'res-4',
        time: '12:00',
        guestName: 'Jonas Dahl',
        email: 'jonas.dahl@stockholm.se',
        phone: '+46 70 555 1234',
        table: 'Table 2',
        partySize: 2,
        status: 'Completed',
        service: 'Lunch',
        notes: 'Lunch service',
    },
    {
        id: 'res-5',
        time: '13:00',
        guestName: 'Astrid Lind',
        email: 'astrid@lind.org',
        phone: '+46 72 333 4455',
        table: 'Table 4',
        partySize: 4,
        status: 'Completed',
        service: 'Lunch',
        notes: 'Dairy intolerance noted',
    },
];
